language: scala
sudo: false
scala:
  - 2.11.7
jdk:
  - oraclejdk8
script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test && sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
after_success:
  - bash <(curl -s https://codecov.io/bash)
